# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnixTime', models.CharField(max_length=39)),
                ('data', models.CharField(max_length=901)),
                ('snr', models.CharField(max_length=39)),
                ('linkQuality', models.CharField(max_length=39)),
                ('regularTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Datatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigfoxID', models.CharField(max_length=20)),
                ('apiLogin', models.CharField(max_length=100)),
                ('apiPassword', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=200)),
                ('function_description', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=200)),
                ('library_author', models.CharField(max_length=200)),
                ('library_description', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='belongs_to_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Library'),
        ),
        migrations.AddField(
            model_name='data',
            name='Device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Device'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
    ]
